name: CI - Angular Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      # <-- CHANGED: run npm script (uses local ng from node_modules)
      - name: Build (production) with correct base-href
        run: npm run build --if-present -- --configuration production --base-href /angular-builds/

      - name: Show dist contents
        run: ls -la dist || true

      - name: Ensure 404.html for SPA routing
        run: |
          if [ -d "dist/${{ env.REPO_NAME }}" ]; then
            cp dist/${{ env.REPO_NAME }}/index.html dist/${{ env.REPO_NAME }}/404.html || true
          else
            echo "dist/${{ env.REPO_NAME }} not found. Build may have failed."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/${{ env.REPO_NAME }}
          keep_files: false
